---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Second University Village Home Owners Association"
keywords:    "SUVHOA, Second University, Home Owners Association, HOA"
description: "Second University Village Home Owners Association"
source_link: "https://sysadmininator.com/suvhoa"
favicon:     "img/icons8-home-512.png"
touch_icon:  "img/icons8-home-512.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  olive:     '#bea925'
  rnbwred:       '#FF0000'
  rnbworange:    '#FF7F00'
  rnbwyellow:    '#FFFF00'
  rnbwgreen:     '#00FF00'
  rnbwblue:      '#0000FF'
  rnbwindigo:    '#4B0082'
  rnbwviolet:    '#9400D3'

kramdown:
  auto_ids:  false

